spring:
  datasource:
    #    数据库配置
    username: root
    password: 961214
    url: jdbc:mysql://localhost:3306/dental_appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    #    上传文件大小设置
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mvc:
    #    网络图片映射
    static-path-pattern: /image/**
  web:
    resources:
      #      本地图片映射
      static-locations: file:E://IDEA/WorkSpace/Lyeye/IdeaProjects/dental_appointment/photos/notice/

mybatis:
  configuration:
    #    驼峰命名
    map-underscore-to-camel-case: true

#日志
logging:
  level:
    learning: debug
