package com.lyeye.dentalappointmentsystem.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lyeye.dentalappointmentsystem.entity.Administrator;
import com.lyeye.dentalappointmentsystem.entity.AppointmentInfo;
import com.lyeye.dentalappointmentsystem.entity.Hospital;
import com.lyeye.dentalappointmentsystem.entity.User;

import com.lyeye.dentalappointmentsystem.greendao.AdministratorDao;
import com.lyeye.dentalappointmentsystem.greendao.AppointmentInfoDao;
import com.lyeye.dentalappointmentsystem.greendao.HospitalDao;
import com.lyeye.dentalappointmentsystem.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig administratorDaoConfig;
    private final DaoConfig appointmentInfoDaoConfig;
    private final DaoConfig hospitalDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AdministratorDao administratorDao;
    private final AppointmentInfoDao appointmentInfoDao;
    private final HospitalDao hospitalDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        administratorDaoConfig = daoConfigMap.get(AdministratorDao.class).clone();
        administratorDaoConfig.initIdentityScope(type);

        appointmentInfoDaoConfig = daoConfigMap.get(AppointmentInfoDao.class).clone();
        appointmentInfoDaoConfig.initIdentityScope(type);

        hospitalDaoConfig = daoConfigMap.get(HospitalDao.class).clone();
        hospitalDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        administratorDao = new AdministratorDao(administratorDaoConfig, this);
        appointmentInfoDao = new AppointmentInfoDao(appointmentInfoDaoConfig, this);
        hospitalDao = new HospitalDao(hospitalDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Administrator.class, administratorDao);
        registerDao(AppointmentInfo.class, appointmentInfoDao);
        registerDao(Hospital.class, hospitalDao);
        registerDao(User.class, userDao);
    }

    public void clear() {
        administratorDaoConfig.clearIdentityScope();
        appointmentInfoDaoConfig.clearIdentityScope();
        hospitalDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AdministratorDao getAdministratorDao() {
        return administratorDao;
    }

    public AppointmentInfoDao getAppointmentInfoDao() {
        return appointmentInfoDao;
    }

    public HospitalDao getHospitalDao() {
        return hospitalDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
